### ISSUE TITLE
Navidrome chart is not installable with Flux

### ISSUE THREAD

**Issue by kjaleshire** [0xEmma/helm-charts#1]
Because the Navidrome chart begins with an uppercase letter, using [Flux HelmRelease](https://fluxcd.io/flux/use-cases/helm/#getting-started) to install results in this Event message:

```
Warning  InvalidChartReference  8m51s (x2 over 8m53s)  source-controller  invalid chart reference: invalid chart name 'Navidrome': a valid name must be lower case letters and numbers and MAY be separated with dashes (-) or slashes (/)
```

[Helm best practices](https://helm.sh/docs/chart_best_practices/conventions/) suggest all-lowercase letters for chart names.

Many thanks for the chart!

**Comment by 0xEmma** [comment]
Just deployed a new version of that chart 0.0.5 that fixes this!

**Comment by 0xEmma** [comment]
For some reason, github actions isnt wanting to deploy the update to the pages content - will be avail once this action finishes https://github.com/0xEmma/helm-charts/actions/runs/5407615255/jobs/9825825559, most likely caused by https://www.githubstatus.com/
